parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  mocha: true

extends: ['htmlacademy/es6', 'plugin:flowtype/recommended']

plugins: ['flowtype']

rules: {
  indent: ['error', 4]
}