parser:
  babel-eslint

parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  mocha: true

extends: ['plugin:flowtype/recommended']

plugins: ['flowtype']

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

rules:
  indent: ['error', 4]
  semi: 2
