parserOptions:
  sourceType: 'module'

env:
  es6: true
  browser: true
  mocha: true

extends: ['htmlacademy/es6', 'plugin:flowtype/recommended']

plugins: ['flowtype']

settinngs:
  flowtype:
    onlyFilesWithFlowAnnotation: false

rules:
  indent: ['error', 4]
  flowtype/require-valid-file-annotation: [2, 'always']